let emotionalList = [
  {
    id: "1",
    audioPath: require("./audios/Humdard Ek Villain.mp3"),
    name: "Humdard",
    artist: "Arijit Singh",
    movie: "Ek Villain",
    imgPath: require("./images/Ek_Villain.jpg"),
    playImgPath: require("./images/mainplay.png"),
  },
  {
    id: "2",
    audioPath: require("./audios/Khilengi Jahan Bahare Sabhi.mp3"),
    name: "Bhula Dena",
    artist: "Mustafa Zahid",
    movie: "Aashique 2",
    imgPath: require("./images/ashique2.webp"),
    playImgPath: require("./images/mainplay.png"),
  },
  {
    id: "3",
    audioPath: require("./audios/Tujhe Bhula Diya Phir.mp3"),
    name: " Tujhe Bhula Diya",
    artist: "Vishal-Shekha",
    movie: " Anjaana Anjaani",
    imgPath: require("./images/TBDP.jpg"),
    playImgPath: require("./images/mainplay.png"),
  },
  {
    id: "4",
    audioPath: require("./audios/Yahi Hota Pyaar.mp3"),
    name: "Yahi Hota Pyaar",
    artist: "Himesh Reshammiya",
    movie: "Namastey London",
    imgPath: require("./images/NamesteyLondon.webp"),
    playImgPath: require("./images/mainplay.png"),
  },
  {
    id: "5",
    audioPath: require("./audios/Tum Bin.mp3"),
    name: "Tum Bin",
    artist: "Shreya Ghoshal",
    movie: "Sanam Re",
    imgPath: require("./images/Sanama-Re.jpg"),
    playImgPath: require("./images/mainplay.png"),
  },
  {
    id: "6",
    audioPath: require("./audios/O Re Piya.mp3"),
    name: "O Re Piya",
    artist: "Rahat Fateh Ali Khan",
    movie: "Aaja Nachle",
    imgPath: require("./images/O_Re_Piya.jpg"),
    playImgPath: require("./images/mainplay.png"),
  },
  {
    id: "7",
    audioPath: require("./audios/Teri Mitti.mp3"),
    name: "Teri Mitti",
    artist: "B.Praak",
    movie: "Kesari",
    imgPath: require("./images/Teri_Mitti.webp"),
    playImgPath: require("./images/mainplay.png"),
  },
  {
    id: "8",
    audioPath: require("./audios/Do Pal Ki.mp3"),
    name: "Do Pal Ki",
    artist: "Lata Mangeshkar, Sonu Nigam",
    movie: "VeerZaara",
    imgPath: require("./images/VeerZara.webp"),
    playImgPath: require("./images/mainplay.png"),
  },
  {
    id: "9",
    audioPath: require("./audios/Tere Naam.mp3"),
    name: "Tere Naam",
    artist: "Udit Narayan,Alka Yagnik",
    movie: "Tere Naam",
    imgPath: require("./images/Tere_Naam.jpg"),
    playImgPath: require("./images/mainplay.png"),
  },
  {
    id: "10",
    audioPath: require("./audios/Jhonka Hawa Ka.mp3"),
    name: "Jokha Hawa Ka",
    artist: "Hariharan",
    movie: "Hum Dil De Chuke Sanam",
    imgPath: require("./images/HDDCS.jpg"),
    playImgPath: require("./images/mainplay.png"),
  },
  {
    id: "11",
    audioPath: require("./audios/Mann_Bharrya.mp3"),
    name: "Mann Bharrya",
    artist: "B.Prakk",
    movie: "SherShah",
    imgPath: require("./images/Mann_Bharrya.jpg"),
    playImgPath: require("./images/mainplay.png"),
  },
  {
    id: "12",
    audioPath: require("./audios/Aaj-Ibaadat.mp3"),
    name: "Aajh Ibadat",
    artist: "Javed Bashir",
    movie: "Bajirao Mastani",
    imgPath: require("./images/Bajirao_Mastnai.webp"),
    playImgPath: require("./images/mainplay.png"),
  },
  {
    id: "13",
    audioPath: require("./audios/Aa Bhi Jaa Tu Kahin Se.mp3"),
    name: " Aa Bhi Ja",
    artist: "Sonu Nigam",
    movie: "Love Anthems",
    imgPath: require("./images/Sonu_Nigam.webp"),
  },
  {
    id: "14",
    audioPath: require("./audios/Mai Phir Bhi.mp3"),
    name: "Mai Phir Bhi",
    artist: "Arijit Singh",
    movie: "Half GirlFriend",
    imgPath: require("./images/Mai_Phir_Bhi.webp"),
  },

  {
    id: "15",
    audioPath: require("./audios/Beete Lamhein.mp3"),
    name: " Beete Lamhein",
    artist: "KK",
    movie: "The Train",
    imgPath: require("./images/Bete_Lamhein.jpg"),
  },
  {
    id: "16",
    audioPath: require("./audios/Tum Jo Aaye.mp3"),
    name: "Tum Jo Aye",
    artist: "Rahat Fateh Ali Khan",
    movie: "Once Upon A Time In Mumbai",
    imgPath: require("./images/OUATIM.jpg"),
  },
  {
    id: "17",
    audioPath: require("./audios/Kabhi-Yaadon-Mein-Aao.mp3"),
    name: "Kabhi Yaadon",
    artist: "Palak Muchhal, Arijit Singh",
    movie: "Tere Bina",
    imgPath: require("./images/Kabhi Yaadon Mein Aao.jpg"),
  },

  {
    id: "18",
    audioPath: require("./audios/Agar Tum Saath Ho.mp3"),
    name: "Agar Tum Saath",
    artist: "Alka Yagnik, Arijit Singh",
    movie: "Tamasha",
    imgPath: require("./images/Agar-Tum-Saath-Ho-Tamasha.jpg"),
  },
  {
    id: "19",
    audioPath: require("./audios/Uska Hi Banana.mp3"),
    name: "Uska Hi Bna",
    artist: "Chirrantan Bhatt",
    movie: "1920 Evil Returns",
    imgPath: require("./images/Uska Hi Banana.jpg"),
  },
  {
    id: "20",
    name: " Ye Laal Ishq",
    audioPath: require("./audios/Laal Ishq Goliyon Ki Raasleela Ram Leela.mp3"),
    artist: "Arijit Singh",
    movie: "Ram Leela",
    imgPath: require("./images/Laal-Ishq.jpg"),
  },
  {
    id: "21",
    audioPath: require("./audios/Phir Mohabbat Murder 2.mp3"),
    name: "Phir Mohabbat",
    artist: "Arijit, Mohammed Irfan,Saim Bhatt",
    movie: "Murder 2",
    imgPath: require("./images/Phir-Mohabbat.jpg"),
  },
];

export { emotionalList };
