let musicList_1 = [
  {
    id: "01",
    audioPath: require("./audios/Tera Hi.mp3"),
    name: "Tera Hi Bas Hona Chaahoon",
    artist: "JoJo",
    movie: "Haunted",
    imgPath: require("./images/haunted.webp"),
    playImgPath: require("./images/play.png"),
    //pauseImgPath: require("./images/pause_2.png"),
  },
  {
    id: "02",
    audioPath: require("./audios/Sun raha hai na tu.mp3"),
    name: "Sun Raha Hai Na",
    artist: "Ankit Tiwari",
    movie: "Ashique 2",
    imgPath: require("./images/ashique2.webp"),
    playImgPath: require("./images/play.png"),
    //pauseImgPath: require("./images/pause_2.png"),
  },
  {
    id: "03",
    audioPath: require("./audios/Hmk.mp3"),
    name: "Hamari Adhuri Kahani",
    artist: "Arijit Singh",
    movie: "Hamari Adhuri Kahani",
    imgPath: require("./images/hak.webp"),
    playImgPath: require("./images/play.png"),
    //pauseImgPath: require("./images/pause_2.png"),
  },
  {
    id: "04",
    audioPath: require("./audios/Jab Bhi Teri.mp3"),
    name: "Jab Bhi Teri Yaad",
    artist: "Ishoj",
    movie: "Album",
    imgPath: require("./images/jty.webp"),
    playImgPath: require("./images/play.png"),
    //pauseImgPath: require("./images/pause_2.png"),
  },
  {
    id: "05",
    audioPath: require("./audios/Mohabbat.mp3"),
    name: "Mohabbat Ho Na Jaye",
    artist: "Kumar Sanu,Alka Yagini",
    movie: "Kasoor",
    imgPath: require("./images/kasoor.webp"),
    playImgPath: require("./images/play.png"),
    //pauseImgPath: require("./images/pause_2.png"),
  },
  {
    id: "06",
    audioPath: require("./audios/Kham.mp3"),
    name: "Khamoshiyaan",
    artist: "Arijit Singh",
    movie: "Khamoshiyaan",
    imgPath: require("./images/kham.webp"),
    playImgPath: require("./images/play.png"),
    //pauseImgPath: require("./images/pause_2.png"),
  },
  {
    id: "07",
    audioPath: require("./audios/Hum.mp3"),
    name: "Humnava",
    artist: "Papon",
    movie: "Hamari Adhuri Kahani",
    imgPath: require("./images/hh.webp"),
    playImgPath: require("./images/play.png"),
    //pauseImgPath: require("./images/pause_2.png"),
  },
  {
    id: "08",
    audioPath: require("./audios/Naina.mp3"),
    name: "Naina",
    artist: "Arijit Singh",
    movie: "Dangal",
    imgPath: require("./images/naina.webp"),
    playImgPath: require("./images/play.png"),
    //pauseImgPath: require("./images/pause_2.png"),
  },
  {
    id: "09",
    audioPath: require("./audios/MainDhoondne.mp3"),
    name: "Mai Dhoondne Ko Zamane Me",
    artist: "Arijit Singh",
    movie: "Heartless",
    imgPath: require("./images/heartless.webp"),
    playImgPath: require("./images/play.png"),
    //pauseImgPath: require("./images/pause_2.png"),
  },
  {
    id: "10",
    audioPath: require("./audios/Pal Pal.mp3"),
    name: "Pal Pal Dil K Paas",
    artist: "Kishore Kumar",
    movie: "BlackMail",
    imgPath: require("./images/dil k paas.jpg"),
    playImgPath: require("./images/play.png"),
    //pauseImgPath: require("./images/pause_2.png"),
  },
  {
    id: "11",
    audioPath: require("./audios/Milne hai.mp3"),
    name: "Milne Hai Mujhse Aai",
    artist: "Arijit Singh",
    movie: "Ashique 2",
    imgPath: require("./images/milne hai.jpg"),
    playImgPath: require("./images/play.png"),
    //pauseImgPath: require("./images/pause_2.png"),
  },
  {
    id: "12",
    audioPath: require("./audios/Shiddat.mp3"),
    name: "Shiddat Bana Lu Tujhe",
    artist: "Manan Bhardwaj",
    movie: "Shiddat",
    imgPath: require("./images/shiddat.jpg"),
    playImgPath: require("./images/play.png"),
    //pauseImgPath: require("./images/pause_2.png"),
  },
];

let musicList_2 = [
  {
    id: "13",
    audioPath: require("./audios/SariDunia.mp3"),
    name: "Sari Dunia ",
    artist: "B.Praak",
    movie: "Animal",
    imgPath: require("./images/sari dunia.webp"),
  },
  {
    id: "14",
    audioPath: require("./audios/HareKrishna.mp3"),
    name: "Hare Krishna ",
    artist: "Palak Muchhal",
    movie: "Album",
    imgPath: require("./images/hk.webp"),
  },
  {
    id: "15",
    audioPath: require("./audios/OMahi.mp3"),
    name: "O Mahi ",
    artist: "Arijit Singh",
    movie: "Dunki",
    imgPath: require("./images/Omahi.webp"),
  },
  {
    id: "16",
    audioPath: require("./audios/SunaSuna.mp3"),
    name: "Suna Suna",
    artist: "Shreya Goshal",
    movie: "Krishna Cottage",
    imgPath: require("./images/krishnacottage.webp"),
  },
  {
    id: "17",
    audioPath: require("./audios/SaansonKo.mp3"),
    name: "Sansoon Ko",
    artist: "Arijit Singh",
    movie: "Zid",
    imgPath: require("./images/zid.webp"),
  },

  {
    id: "18",
    audioPath: require("./audios/Bhagwankahan.mp3"),
    name: "Bhagwan Hai",
    artist: "Sonu Nigam",
    movie: "PK",
    imgPath: require("./images/bhagwan.webp"),
  },
  {
    id: "19",
    audioPath: require("./audios/Husn.mp3"),
    name: "Husn",
    artist: "Anuv Jain",
    movie: "Album",
    imgPath: require("./images/husn.webp"),
  },
  {
    id: "20",
    name: "Kal Ho Na Ho",
    audioPath: require("./audios/KalHoNaHo.mp3"),
    artist: "Sonu Nigam",
    movie: "Kal Ho Na Ho",
    imgPath: require("./images/kl ho na ho.webp"),
  },
  {
    id: "21",
    audioPath: require("./audios/Tune.mp3"),
    name: "Tune Jo Na Kaha",
    artist: "Mohit Chauhan",
    movie: "NeW York",
    imgPath: require("./images/tunejo.webp"),
  },
];

export { musicList_1, musicList_2 };
