let weddingList = [
  {
    id: "1",
    audioPath: require("./audios/Taaron Ka Chamakta.mp3"),
    name: "Taroon Ka Chamakta Gahna Ho",
    artist: "Udit Nrayan",
    movie: "Hum Tumhare Hai Sanam",
    imgPath: require("./images/taroon ka.webp"),
    playImgPath: require("./images/mainplay.png"),
  },
  {
    id: "2",
    audioPath: require("./audios/Chhote_Chhote_Bhaiyyon_Ke.mp3"),
    name: "Chote Chote Bhaiyoon Ke",
    artist: " Udit Narayan , Kumar Sanu",
    movie: "Hum Saath Saath Hain",
    imgPath: require("./images/hum sath sath hai.jpg"),
    playImgPath: require("./images/mainplay.png"),
   
  },
  {
    id: "3",
    audioPath: require("./audios/Sajan-Sajan-Teri-Dulhan.mp3"),
    name: "Sajan Sajan Teri Dulhan",
    artist: "Dj Sid Jhansi",
    movie: "Aarzoo",
    imgPath: require("./images/Sajan-Sajan.webp"),
    playImgPath: require("./images/mainplay.png"),
   
  },
  {
    id: "4",
    audioPath: require("./audios/Teri Dulhan.mp3"),
    name: "Teri Dulhan Sajaungi",
    artist: "Alka Yagini",
    movie: "Barsaat",
    imgPath: require("./images/Barsaat.jpg"),
    playImgPath: require("./images/mainplay.png"),
   
  },
  {
    id: "5",
    audioPath: require("./audios/Kahe-Tose-Sajna.mp3"),
    name: "Kahe To Se Sajna",
    artist: "Sharda Sinha",
    movie: "Maine Pyar Kiya",
    imgPath: require("./images/MainePyarrKiya.webp"),
    playImgPath: require("./images/mainplay.png"),
   
  },
  {
    id: "6",
    audioPath: require("./audios/Mubarak_Ho_Tumko.mp3"),
    name: "Mubarak Ho Tumko",
    artist: "Udit Narayan",
    movie: "Haan Maine Bhi Pyaar Kiya",
    imgPath: require("./images/Mubarak_Ho.jpg"),
    playImgPath: require("./images/mainplay.png"),
   
  },
  {
    id: "7",
    audioPath: require("./audios/Aaja Shaam Hone Aaee.mp3"),
    name: "Aaja Saam Hone Aaee",
    artist: "S.P.Balasubrahmanyam",
    movie: "Maine Pyar Kiya",
    imgPath: require("./images/MainePyarrKiya.webp"),
    playImgPath: require("./images/mainplay.png"),
   
  },
  {
    id: "8",
    audioPath: require("./audios/Mere_Yaar.mp3"),
    name: "Mere Yaar Ki Saadi Hai",
    artist: "Udit Narayan",
    movie: "Mere Yaar Ki Saadi Hai",
    imgPath: require("./images/Mere Yaar Ki Saadi Hai.webp"),
    playImgPath: require("./images/mainplay.png"),
   
  },
  {
    id: "9",
    audioPath: require("./audios/SoniSoni.mp3"),
    name: "Soni Soni",
    artist: "Udit Narayan",
    movie: "Mohabbatein",
    imgPath: require("./images/Mohabbatein.webp"),
    playImgPath: require("./images/mainplay.png"),
   
  },
  {
    id: "10",
    audioPath: require("./audios/Hum Khush Hue.mp3"),
    name: "Hum Khush Hue",
    artist: "Mohammed Aziz, Kumar Sanu",
    movie: "Ek Rishtaa",
    imgPath: require("./images/Rishtaa.jpg"),
    playImgPath: require("./images/mainplay.png"),
   
  },
  {
    id: "11",
    audioPath: require("./audios/Dulhe Ka Sehra.mp3"),
    name: "Dulhe Ka Sehra",
    artist: "Nusrat Fateh Ali Khan",
    movie: "Dhadkan",
    imgPath: require("./images/Dhadkan.jpg"),
    playImgPath: require("./images/mainplay.png"),
   
  },
  {
    id: "12",
    audioPath: require("./audios/Mehndi Laga Ke Rakhna Dilwale Dulhania Le Jayenge.mp3"),
    name: "Mehndi Laga Ke Rakhna",
    artist: "Lata Mangeshkar, Udit Narayan",
    movie: "Dilwale Dulhania Le Jayenge",
    imgPath: require("./images/DDLJ.jpg"),
    playImgPath: require("./images/mainplay.png"),
   
  },
  {
    id: "13",
    audioPath: require("./audios/Sabki Baaratein.mp3"),
    name: "Sabki Baaratein",
    artist: "Jaspinder Narula",
    movie: "Jaanam Samjha Karo",
    imgPath: require("./images/Janaam.jpg"),
  },
  {
    id: "14",
    audioPath: require("./audios/Aaye Ho Meri Zindagi Mein.mp3"),
    name: "Meri Zindagi",
    artist: "Udit Narayan",
    movie: "Raja Hindustani",
    imgPath: require("./images/Raja_Hindustani.jpg"),
  },

  {
    id: "15",
    audioPath: require("./audios/Pairon Mein Bandhan Hai.mp3"),
    name: "Pairon Mein",
    artist: "Udbhav",
    movie: "Mohabbatein",
    imgPath: require("./images/Mohabbatein.webp"),
  },
  {
    id: "16",
    audioPath: require("./audios/Wah Wah Ramji.mp3"),
    name: "Wah Wah Ram Ji",
    artist: "S.P.Balasubrahmanyam",
    movie: "Hum Aapke Hai Kaun",
    imgPath: require("./images/Wah Wah.jpg"),
  },
  {
    id: "17",
    audioPath: require("./audios/Tere Dware Pe Aai Baraat.mp3"),
    name: "Tere Dware Pe",
    artist: "Ravindra Jain",
    movie: "Vivah",
    imgPath: require("./images/Vivah.jpg"),
  },

  {
    id: "18",
    audioPath: require("./audios/Jaane Dil Mein.mp3"),
    name: "Jaane Dil Mein",
    artist: "Rahul Sharma",
    movie: "Mujhse Dosti Karoge",
    imgPath: require("./images/MDK.webp"),
  },
  {
    id: "19",
    audioPath: require("./audios/Saajanji Ghar Aaye.mp3"),
    name: "Saajanji Ghar",
    artist: "Alka Yagnik",
    movie: "Kuch Kuch Hota Hai",
    imgPath: require("./images/KKGH.webp"),
  },
  {
    id: "20",
    name: "Tujhko Hi",
    audioPath: require("./audios/Tujhko Hi Dullhan Banaonga.mp3"),
    artist: "Sonu Nigam,Alka Yagnik",
    movie: "Chalo Ishq Ladaaye",
    imgPath: require("./images/THDBG.jpg"),
  },
  {
    id: "21",
    audioPath: require("./audios/Ajj Din Chadheya.mp3"),
    name: "Ajj Din Chadheya",
    artist: "Rahat Fateh Ali Khan",
    movie: "Love Aaj Kal",
    imgPath: require("./images/Love_Ajh_Kal.jpg"),
  },
];

export { weddingList };
